### ISSUE TITLE
bug: sub-itens de menu devem vir acompanhados de font-awesome icon

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#1]
O mesmo acontece com searh bar: 

![selecao_084](https://cloud.githubusercontent.com/assets/641411/22371466/659e59a2-e47e-11e6-8155-4a7396dcb59b.png)

Veja código: 

![selecao_085](https://cloud.githubusercontent.com/assets/641411/22371359/ed9613aa-e47d-11e6-8b61-b5e2caa6e792.png)

**Comment by gusgustavo** [comment]
Resolvido.
