### ISSUE TITLE
Bug: título de notícia do carrossel com quebra de linha

### ISSUE THREAD

**Issue by gusgustavo** [robertkapa/institutotim-header-footer#15]

**Comment by robertkapa** [comment]
Alguns títulos com mais de 20 caracteres foram impactados com as mudanças. É necessário diminuir o h1 do título de notícias do header para manter tudo em uma única linha. Para isso basta alterar o item font-size da classe exemplificada abaixo para 20px;

![selecao_109](https://cloud.githubusercontent.com/assets/641411/22432216/586fb42c-e6fb-11e6-8b48-d382aa003fb1.png)

```
section#main-section .highlight-wrapper .highlight-container .content h1 {
font-size: 20px; 
}
```

**Comment by gusgustavo** [comment]
Ok. Alterado.
