### ISSUE TITLE
Embaixo do carrossel, o botão “Trabalho” caiu para uma segunda linha.

### ISSUE THREAD

**Issue by gusgustavo** [robertkapa/institutotim-header-footer#16]

**Comment by gusgustavo** [comment]
Resolvido alterando o main.css

**Comment by robertkapa** [comment]
ainda com problema no chrome: 

![selecao_099](https://cloud.githubusercontent.com/assets/641411/22430139/4220035e-e6f4-11e6-8ff3-8060d236120c.png)

**Comment by gusgustavo** [comment]
@robertkapa, qual é a resolução do monitor utilizada?

**Comment by robertkapa** [comment]
o problema não é o monitor. Testei em vários monitores e dei ctrl+0 para ver a visão de 100% do site. Testei em monitor 1920x1080 com chromium e problema persiste.

**Comment by gusgustavo** [comment]
Abri em computadores diferentes e monitores diferentes e não consigo ver esse bug.

Ele persiste aí? Qual a versão do navegador, resolução do monitor e sistema operacional?

**Comment by robertkapa** [comment]
resolvido!
