### ISSUE TITLE
bug: itens do rodapé devem refletir os itens e sub-itens do menu

### ISSUE THREAD

**Issue by gusgustavo** [robertkapa/institutotim-header-footer#18]

**Comment by robertkapa** [comment]
Código do footer com vistas ao site do Instituto TIM

`
    
    <footer class="section section-primary">
      <div class="section">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="section">
                <div class="container">
                  <div class="row">
                    <div class="col-md-8 col-md-8 col-sm-12 col-xs-12">
                      <div class="col-md-3 col-md-3 col-sm-6 col-xs-12 text-left">
                        <p class="footertitle">Sobre</p>
                        <p class="">Missão e Princípios</p>
                        <p class="">Governança</p>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 text-left footerborder-left">
                        <p class="footertitle">Iniciativas</p>
                        <p class="">Projetos</p>
                        <p class="">Soluções</p>
                        <p class="">Editais</p>                        
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 text-left footerborder-left">
                        <p class="footertitle">Comunicação</p>
                        <p class="">Imprensa</p>
                        <p class="">Clipping</p>
                        <p class="">Manual da Marca</p>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 text-left footerborder-left">
                        <p class="footertitle">Notícias</p>
                        <p class="footertitle">Contato</p>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 text-center footerborder-left">
                      <div class="row">
                        <br>
                        <br>
                        <a href="https://institutotim.org.br"><img src="img/logo_header_institutotim.png"></a>

                      </div>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
             <div class="col-md-12 col-md-12 col-sm-12 col-xs-12 text-center footertitle">
               <div class="row">
                  <br><br><br><br><br>
                 Copyright TIM Celular 2016 - Todos os direitos reservados.
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    
`

**Comment by robertkapa** [comment]
![selecao_111](https://cloud.githubusercontent.com/assets/641411/22432943/bf1832a6-e6fd-11e6-841e-52dc98b5765e.png)

**Comment by anatolezano** [comment]
Pessoal, mais um adendo a esse item: a primeira coluna está mais alta em relação às outras, os itens estão desalinhados.

**Comment by robertkapa** [comment]
quebrado no firefox:

![selecao_002](https://cloud.githubusercontent.com/assets/641411/23762771/ec565de2-04d5-11e7-9cbe-2044efc73d39.png)

**Comment by anatolezano** [comment]
Gente, no meu não está corrigido. Ainda continua com a primeira coluna desalinhada, não está escrito "Sobre" ao invés de "Conheça o Instituto TIM", não está escrito "Imprensa" ao invés de "Assessoria de imprensa" e os itens "Notícias" e "Contato" não estão na fonte azul e dispostos da maneira como o Felipe postou que deveria ser.

**Comment by anatolezano** [comment]
Olá, @gusgustavo, o @robertkapa me informou que você comentou que finalizou as issues dos sites IT, TFC e AWC, mas vou reforçar aqui os pontos que devem ser corrigidos e ainda não foram, ok? Esse tópico é um deles, tudo que coloquei no último comentário, feito há duas semanas e sem retorno de ninguém, ainda não foi corrigido. Vou comentar nos outros tópicos para atualizá-los também.
