### ISSUE TITLE
bug: no firefox, menu aparece desolocado

### ISSUE THREAD

**Issue by gusgustavo** [robertkapa/institutotim-header-footer#19]
Resolução

Necessita alterar o padding (linha 42 do institutotim.css) e na versão menor (linha 271) 
.navbar-default .navbar-nav > li > a 
padding: 1px 0px 5px 20px;

**Comment by robertkapa** [comment]
![selecao_112](https://cloud.githubusercontent.com/assets/641411/22433072/3e301040-e6fe-11e6-92a2-0c491d6b27ca.png)

**Comment by gusgustavo** [comment]
Arrumado
