### ISSUE TITLE
bug: distância no footer

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#2]
Deve existir uma distância entre os conteúdos e o rodapé, bem como a distância entre a frase de copyright e o final da página. 

Comportamento esperado: 
![selecao_087](https://cloud.githubusercontent.com/assets/641411/22372000/a3eb7750-e481-11e6-90f1-3e6c851bc489.png)

Bug: 
![selecao_088](https://cloud.githubusercontent.com/assets/641411/22372011/b5f5907a-e481-11e6-9463-5d6df7d2b0d6.png)

**Comment by gusgustavo** [comment]
Corrigido
