### ISSUE TITLE
Página do Mapas Culturais com imagens desalinhadas

### ISSUE THREAD

**Issue by gusgustavo** [robertkapa/institutotim-header-footer#27]

**Comment by gusgustavo** [comment]
Possivelmente em razão do conteúdo bloqueado pois não está sendo fornecido em https. 
Ver erro:

Mixed Content: The page at 'https://institutotim.org.br/project/mapas-culturais/' was loaded over HTTPS, but requested an insecure script 'http://platform.twitter.com/widgets.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by robertkapa** [comment]
parece erro de css...

**Comment by gusgustavo** [comment]
@robertkapa, veja agora se resolveu.

**Comment by robertkapa** [comment]
ok! resolvido.
