### ISSUE TITLE
inserir overtop link para english version / portuguese version

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#3]
![selecao_089](https://cloud.githubusercontent.com/assets/641411/22372234/a92b5234-e482-11e6-8916-e3461bf149ca.png)

![selecao_090](https://cloud.githubusercontent.com/assets/641411/22372238/aea8478a-e482-11e6-8b8b-cf0346b13b4a.png)

**Comment by gusgustavo** [comment]
Link inserido para a versão em inglês

**Comment by gusgustavo** [comment]
Veja se assim está ok.

**Comment by robertkapa** [comment]
Do modo como está funciona. Mas no html/css do modelo há uma classe que alinha melhor este item. Atualmente está desalinhado. Ver último commit: https://github.com/robertkapa/institutotim-header-footer/commit/e827aa08b74d40f6ee351b770db1550f45a0a3d1

![selecao_106](https://cloud.githubusercontent.com/assets/641411/22431807/f76486d6-e6f9-11e6-914d-79071720d6c1.png)


![selecao_107](https://cloud.githubusercontent.com/assets/641411/22431835/13046c44-e6fa-11e6-9db4-e97df6f9de39.png)

**Comment by gusgustavo** [comment]
@robertkapa, nos sites timtec, tfc, awc, também deve aparecer o botão inglês/portugues?

**Comment by robertkapa** [comment]
@gusgustavo Não, pois nesses sites não há versão em dois idiomas.

**Comment by gusgustavo** [comment]
ok!
