### ISSUE TITLE
[IT] Página de resultados da busca: bug no overtop

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#30]

**Comment by gusgustavo** [comment]
Resolvido.

**Comment by anatolezano** [comment]
A fonte do botão "English"/"Português" ainda aumenta quando fazemos a busca:

![image](https://cloud.githubusercontent.com/assets/25586548/22693378/306c42da-ed2a-11e6-893f-1aaf9c17721f.png)

![image](https://cloud.githubusercontent.com/assets/25586548/22693392/39f57efc-ed2a-11e6-842f-cee7872b113d.png)
