### ISSUE TITLE
[IT] seção de Projetos -> Ensino -> os boxes dos projetos aparecem erroneamente alinhados a direita

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#31]

**Comment by anatolezano** [comment]
O site em inglês está com esse mesmo problema de alinhamento, tanto em “Applications” quanto em “Education”

**Comment by robertkapa** [comment]
Como resolver (dica do @GustavoVS):

1 - Acrescentar essa classe no css customizado: 

.row-flex {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display:         flex;
    flex-wrap: wrap;
  }

2 - Chamar essa classe na row que engloba os boxes: 

![selecao_125](https://cloud.githubusercontent.com/assets/641411/22657317/346c82c6-ec7d-11e6-97b7-26feb04303ff.png)

**Comment by robertkapa** [comment]
Testei a solução acima e funcionou.

**Comment by gusgustavo** [comment]
Resolvido com a solução acima.
