### ISSUE TITLE
[IT] Projetos Concluídos - links quebrados

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#36]
Nos ícones dos projetos concluídos, não dá para clicar na foto e nem no título para saber mais, somente na linha fina e no botão saiba mais.Nos ícones dos projetos concluídos, não dá para clicar na foto e nem no título para saber mais, somente na linha fina e no botão saiba mais.

https://institutotim.org.br/project/

![selecao_117](https://cloud.githubusercontent.com/assets/641411/22653996/792b6374-ec72-11e6-99b8-33c094c06e69.png)

**Comment by gusgustavo** [comment]
@robertkapa, veja se está funcionando agora.

**Comment by robertkapa** [comment]
resolvido!
