### ISSUE TITLE
[IT] bug: ícone do Twitter

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#37]
logo antes de começar os textos, abaixo dos títulos, não está aparecendo o ícone do twitter. Só aparece um botão escrito Twitter e os ícones do Facebook e do Google +. Antes aparecia normalmente. 

![selecao_118](https://cloud.githubusercontent.com/assets/641411/22654138/fad1b9f0-ec72-11e6-88e0-5264aced3f3a.png)

**Comment by gusgustavo** [comment]
Resolvido, porém isso era devido a uma requisição HTTP e a regra restrita do SSL e não a implementação do novo header e footer.

**Alteração no arquivo:** parts/share.php e incluído HTTPS.
