### ISSUE TITLE
[IT] Fotos da home no layout inglês com problema

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#38]
As fotos dos projetos na home da página em inglês estão embaçadas, além de também estarem em um tamanho maior do que na página em português.

**Comment by robertkapa** [comment]
@anatolezano acho que o fato do tamanho estar diferente está causando essa sensação de "embasamento". Provavelmente a foto está sendo "esticada" e isso dá essa sensação. Acho que para esse item e para os demais, precisamos sempre de um ambiente "original" para fazer comparações. 

@gusgustavo acho que seria importante manter ambientes originais em paralelo as mudanças para podermos "consultar" e ver o que está errado. Vou abrir essa issue.

**Comment by gusgustavo** [comment]
@robertkapa, limpa o cache do navegador e veja se continua com esse erro.

**Comment by robertkapa** [comment]
Sim, o problema persiste. 

Como deveria ser: 
![selecao_029](https://cloud.githubusercontent.com/assets/641411/22738358/4074cbc4-edee-11e6-8337-c9acdf9c1977.png)

Como está (ocorre apenas no template em inglês, por hora): 
![selecao_028](https://cloud.githubusercontent.com/assets/641411/22738365/45b4fe4c-edee-11e6-8430-2ec95e98c450.png)

**Comment by robertkapa** [comment]
resolvido.

**Comment by anatolezano** [comment]
Aqui no meu computador está igual... As fotos continuam esticadas.

**Comment by anatolezano** [comment]
Não foi resolvido.
