### ISSUE TITLE
[IT] A frase “O que você procura?”, na caixa de busca, aparece cortada no Firefox.

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#39]

**Comment by gusgustavo** [comment]
Resolvido no institutotim.org.br

Alterado no arquivo instituto-tim.css, font-size e height.


.search input {
  width: 100%;
  height: 34px;
  background: #fff;
  border: 1px solid #fff;
  border-radius: 4px;
  font-size: 9pt;
}
