### ISSUE TITLE
novo item na class navbar

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#4]
![selecao_093](https://cloud.githubusercontent.com/assets/641411/22372436/ca99b310-e483-11e6-996a-c70cd3c5055b.png)

Isso fará com que o menu fique sempre em letra maiúscula(uppercase) e o rodapé sempre em Titlecase (primeira maiúscula e o resto minuscula). Fazer mudança no produção.

**Comment by gusgustavo** [comment]
Feito

**Comment by robertkapa** [comment]
Esse código deveria fazer com que os itens de menu, mesmo escritos em caixa baixa, fossem transformados em maiúsculas. 

![selecao_100](https://cloud.githubusercontent.com/assets/641411/22430558/d062d92e-e6f5-11e6-9fa3-4ce262adfb0f.png)

**Comment by robertkapa** [comment]
O código mantém os itens de menu em upper case, mas no footer deve estar em Title Case manualmente. Estou reabrindo para que seja corrigido. É necessário entrar no painel e reescrever em **T**itle **C**ase

**Comment by gusgustavo** [comment]
Ok, header em uppercase e footer em title case.

**Comment by robertkapa** [comment]
ok
