### ISSUE TITLE
[all] Replicar sites originais e apontar para outros endereços a fim de ter um comparativo

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#40]
- [x] Criar domínio http://it.conexaobrasil.org e apontar para 45.79.167.34 
- [x] Criar domínio http://tfc.conexaobrasil.org e apontar para 45.79.167.34 
- [x] Criar domínio http://awc.conexaobrasil.org e apontar para 45.79.167.34 
- [x] Criar domínio http://timtec.conexaobrasil.org e apontar para 45.79.9.148 
- [x] Clonar site http://institutotim.org.br para  http://it.conexaobrasil.org
- [x] Clonar site http://timfazciencia.com.br para  http://tfc.conexaobrasil.org
- [x] Clonar site https://awc.institutotim.org.br para  http://awc.conexaobrasil.org
- [x] Clonar site http://timtec.com.br para  http://timtec.conexaobrasil.org

Para @gusgustavo:

- [x] No servidor 45.79.167.34, apontar o endereço http://it.conexaobrasil.org para o site do Instituto TIM (favor deixar o  it.conexaobrasil.org igual ao original) e fazer alteração na base de dados do wp para que atenda ao endereço http://it.conexaobrasil.org;

- [x] No servidor 45.79.167.34, apontar o endereço http://tfc.conexaobrasil.org para o site do Tim Faz Ciência e fazer alteração na base de dados do wp para que atenda ao endereço http://tfc.conexaobrasil.org;

- [x] No servidor 45.79.167.34, apontar o endereço http://awc.conexaobrasil.org para o site do Academic Working Capital e fazer alteração na base de dados do wp para que atenda ao endereço http://awc.conexaobrasil.org;

- [x] No servidor 45.79.9.148 , apontar o endereço http://timtec.conexaobrasil.org para o site do TIMTec e fazer alteração na base de dados do wp para que atenda ao endereço http://timtec.conexaobrasil.org;

obs: as senhas permanecem as mesmas.

**Comment by vitor-kato** [comment]
- [x] Todos os sites estão no ar e funcionando corretamente. :sparkles:
