### ISSUE TITLE
[tfc] Bug: sub-itens de menu com defeito

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#42]
![captura de tela de 2017-02-06 15 34 06](https://cloud.githubusercontent.com/assets/641411/22658658/076ae7ea-ec82-11e6-80b6-4fe69ae121c6.png)

![captura de tela de 2017-02-06 15 34 01](https://cloud.githubusercontent.com/assets/641411/22658667/0bbd707e-ec82-11e6-8701-a959badac8f4.png)

**Comment by gusgustavo** [comment]
Ok, em andamento.

**Comment by robertkapa** [comment]
resolvido.
