### ISSUE TITLE
[tfc] bug: na home, bullets aparecem quebrados

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#43]
Como deve ser: 
![selecao_130](https://cloud.githubusercontent.com/assets/641411/22658784/715b2b88-ec82-11e6-8b98-d7cadb331493.png)

Como está: 
![selecao_129](https://cloud.githubusercontent.com/assets/641411/22658791/74c38a4a-ec82-11e6-85b3-b52782d0932e.png)

**Comment by anatolezano** [comment]
É importante notar que as fontes também estão incorretas em tamanho e estilo.

**Comment by anatolezano** [comment]
Aliás, uma pergunta: as fontes dos textos também irão mudar com o novo site, assim como no IT?

**Comment by robertkapa** [comment]
> Aliás, uma pergunta: as fontes dos textos também irão mudar com o novo site, assim como no IT? Porque elas estão diferentes agora.

sim. No novo guide as fontes são diferentes.

**Comment by anatolezano** [comment]
Mas só dos textos ou as da home também? Porque as da home ficaram feias, sem destaque :(

**Comment by robertkapa** [comment]
> Mas só dos textos ou as da home também? Porque as da home ficaram feias, sem destaque :(

De tudo.

**Comment by anatolezano** [comment]
Poxa, que pena, essa nova fonte não ficou boa na home de TFC :(

**Comment by robertkapa** [comment]
resolvido.
