### ISSUE TITLE
[tfc] footer quebrado

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#45]
- [ ] Itens com fonte desalinhada (alguns itens estão com maiúscula, enquanto outros com minúscula...). Todos os itens deve ser Title Case (primeira maiúscula e o restante minúscula).
![selecao_002](https://cloud.githubusercontent.com/assets/641411/22659625/79febc02-ec85-11e6-8b8e-4c759fe50dc6.png)

- [ ] Os itens não refletem os mesmos itens do menu

- [ ] As linhas laterais que separam os itens/boxes estão quebradas. Deveriam aparecer verticais e aparecem horizontais e jogadas. 
![selecao_003](https://cloud.githubusercontent.com/assets/641411/22659653/949d1c7a-ec85-11e6-9c0d-3d53ee18d9ee.png)

**Comment by robertkapa** [comment]
resolvido.

**Comment by anatolezano** [comment]
Gente o footer está com vários itens incorretos. As sete operações estão abaixo do item "O que é TIM Faz Ciência" (que ainda está ligeiramente mais alto que os outros itens), as notícias parecem um subitem de "Queremos ouvir você" (que deveria ser "Fale conosco", na nova mudança), tem um item e subitem da Galeria dos Pensadores desnecessariamente... Enfim, é só olhar, comparar com o header e ver que há muito pra corrigir.
