### ISSUE TITLE
[tfc]home -> itens do box "para saber+" quebrado

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#46]
- [x] Links não funcionam
- [x] js que fazia abrir o conteúdo no box lateral não opera

![selecao_004](https://cloud.githubusercontent.com/assets/641411/22659794/2a185738-ec86-11e6-9ec7-a69cb80dddaf.png)

**Comment by gusgustavo** [comment]
Resolvido

**Comment by anatolezano** [comment]
O espaçamento entre os itens do box também está bem diferente do atual. Isso será resolvido? (não sei se essa demanda se encaixa nessa issue ou se seria em outra.)

**Comment by robertkapa** [comment]
@anatolezano pelo que pude verificar, o espaçamento não mudou, o que mudou foi a fonte e por isso dá essa impressão. A única pendência com relação a esse box é a centralização do botão "ler mais matérias". 

Como deve ser: 
![selecao_103](https://cloud.githubusercontent.com/assets/641411/22787461/9d276d7e-eec3-11e6-8613-1868ace4f760.png)

Como está: 
![selecao_102](https://cloud.githubusercontent.com/assets/641411/22787469/a344251c-eec3-11e6-8a05-dd2137e9db6b.png)
