### ISSUE TITLE
[tfc] bug - layout do botão "responder" está errado

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#47]
Layout esperado: 
![selecao_005](https://cloud.githubusercontent.com/assets/641411/22659934/bd8770b2-ec86-11e6-8c43-a6cd7060f1dd.png)

Como está: 
![observar tim faz ciencia](https://cloud.githubusercontent.com/assets/641411/22659923/b7096aba-ec86-11e6-8fbf-0224a1808434.png)

**Comment by gusgustavo** [comment]
Resolvido
