### ISSUE TITLE
[tfc] bug - internas sem modal para vídeos laterais

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#48]
Em algumas páginas internas há vídeos como widgets laterais. Ao clicar nesses vídeos, o site deve abrir um modal centralizado para play do vídeo. Com a mudança do header, o modal não está mais abrindo. O vídeo está abrindo diretamente no youtube. Isso acontece em todos os lugares onde há vídeos (na home e nas internas). 

Comportamento esperado: 
https://youtu.be/KHFtNQr4r-k

Como está: 
https://youtu.be/reNZCkBCnb4

![selecao_006](https://cloud.githubusercontent.com/assets/641411/22660402/8b89bc6c-ec88-11e6-93a4-1ff3a662828f.png)

**Comment by gusgustavo** [comment]
Ok, resolvido.
