### ISSUE TITLE
[tfc] bug - menu com item marcado

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#49]
![selecao_008](https://cloud.githubusercontent.com/assets/641411/22660569/35d3c280-ec89-11e6-8952-66af1b440d5f.png)
![selecao_007](https://cloud.githubusercontent.com/assets/641411/22660573/3900820e-ec89-11e6-967b-1b8402a572d2.png)

**Comment by gusgustavo** [comment]
Resolvido

**Comment by robertkapa** [comment]
ok
