### ISSUE TITLE
bug: espaçamento dos ítens no rodapé

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#5]
Comportamento esperado: 
![selecao_094](https://cloud.githubusercontent.com/assets/641411/22372502/45ae07ae-e484-11e6-9ead-87bc78be2c66.png)

Como está: 
![selecao_092](https://cloud.githubusercontent.com/assets/641411/22372479/1c021f44-e484-11e6-95c2-a393ad7e2686.png)

**Comment by gusgustavo** [comment]
Resolvido

**Comment by robertkapa** [comment]
Problema persiste no chrome e no firefox. 

Chrome: 

![selecao_103](https://cloud.githubusercontent.com/assets/641411/22430832/9d0a5c72-e6f6-11e6-856f-376ab975cd5b.png)

Firefox: 
![selecao_104](https://cloud.githubusercontent.com/assets/641411/22430841/a295d504-e6f6-11e6-9338-fde11927fb74.png)
