### ISSUE TITLE
[tfc] bug - caixas de vídeo na home

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#50]
Na home, os ítens de vídeo dos boxes "pensadores" e "assistir as aulas" devem seguim link do menu abaixo. 

Como funciona: usuário escolhe um item e clica. A escolha altera item na box do vídeo. 
![selecao_010](https://cloud.githubusercontent.com/assets/641411/22660851/323741d2-ec8a-11e6-9e2b-164c366afb63.png)

Como está: bugado. Ao clicar nos itens, nada acontece. 
![selecao_009](https://cloud.githubusercontent.com/assets/641411/22660867/3eb83588-ec8a-11e6-9331-42e35c84a159.png)

**Comment by anatolezano** [comment]
Esses vídeos também devem aparecer em pop-up, assim como os vídeos das páginas das operações. Agora estão sendo direcionados para a página no YouTube.

**Comment by robertkapa** [comment]
@anatolezano sim. Isso foi reportado. Ver item #48

**Comment by anatolezano** [comment]
Eu vi sim que havia sido reportado no 48, só coloquei um adendo que os da home também estão assim, e não só as páginas internas ;)

**Comment by gusgustavo** [comment]
Ok, os videos voltaram abrir. 
Falta adicionar o icone da lista do player.

**Comment by robertkapa** [comment]
resolvido.
