### ISSUE TITLE
[tfc] bug - header page das internas e barra de migalhas quebrada

### ISSUE THREAD

**Issue by robertkapa** [robertkapa/institutotim-header-footer#52]
Como deve ser (bem alinhado): 
![selecao_012](https://cloud.githubusercontent.com/assets/641411/22661159/7b0970dc-ec8b-11e6-9acb-0f5d0e64888e.png)

Como está: 
![selecao_013](https://cloud.githubusercontent.com/assets/641411/22661168/855655aa-ec8b-11e6-85ed-765a49b31e87.png)

**Comment by gusgustavo** [comment]
@robertkapa, seria melhor se os banners das paginas internas correspondessem com a largura do novo header. Assim o alinhamento ficaria adequado. Voce acha possivel a equipe fazer essas artes?

**Comment by robertkapa** [comment]
@anatolezano quem preparou essas imagens do header das internas? 

Exemplo: 

![selecao_101](https://cloud.githubusercontent.com/assets/641411/22787314/fd17ebe2-eec2-11e6-8d37-2cfb0ec9e41d.png)

**Comment by anatolezano** [comment]
Oi, Felipe, acabei de falar com a Barbara e ela acha que foi ela mesma quem fez. Ela poderia ajustar as artes, mas precisaria de tempo para isso. Como nos falamos, podemos manter as atuais centralizadas por enquanto e depois resolvemos essa questão?

**Comment by robertkapa** [comment]
resolvido.
