### ISSUE TITLE
[TFC] Botão Instituto TIM no header

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#53]
O botão está direcionando para o site da TIM, quando deveria ser para o Instituto TIM. Além disso, a página do Instituto TIM deve abrir em uma nova janela.

![selecao_015](https://cloud.githubusercontent.com/assets/641411/22695715/d32b6e62-ed32-11e6-8412-f05c010a90aa.png)

**Comment by gusgustavo** [comment]
Ok, resolvido.

**Comment by robertkapa** [comment]
ok
