### ISSUE TITLE
[TFC] Home -> Linha verde acima do box Destaques

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#54]
Na home, há uma linha verde que não deveria existir abaixo do box Destaques.

![selecao_016](https://cloud.githubusercontent.com/assets/641411/22695772/0d5ac59c-ed33-11e6-9882-4c873c81ff0b.png)

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/22694002/ae4c3f14-ed2c-11e6-8c1e-eeda5adb0e92.png)

**Comment by gusgustavo** [comment]
Ok, removida.

**Comment by robertkapa** [comment]
ok
