### ISSUE TITLE
[TFC] Home -> Espaço extra abaixo do box de newsletters

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#55]
Há um quadrado rosa abaixo do box "Receba as novidades do site". No site original, sou eu quem controlo o número de imagens que aparecem no box ao lado, "Produção dos Estudantes", por meio de um Widget no WordPress. Quando esse box tem um número de imagens que ultrapassa o box "Receba as novidades do site", aparece esse espaço rosa embaixo, por isso mantenho essa atualização sob controle para ele não aparecer. Atualmente, não está aparecendo no site original, mas está no novo.

![selecao_017](https://cloud.githubusercontent.com/assets/641411/22695830/4f138ba4-ed33-11e6-82d3-d13adb436550.png)

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/22694215/726aeb16-ed2d-11e6-846d-79131182ae5b.png)

**Comment by robertkapa** [comment]
resolvido.
