### ISSUE TITLE
[TFC] Página dos materiais didáticos está quebrada

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#57]
Comportamento esperado: 
http://timfazciencia.com.br/materiais-didaticos/

![baixe os materiais didaticos tim faz ciencia](https://cloud.githubusercontent.com/assets/641411/22696381/eb65eaa0-ed34-11e6-89e3-7385ad6f9450.png)

Como está: 
http://institutotim.gus.computer/materiais-didaticos/

![baixe os materiais didaticos tim faz ciencia2](https://cloud.githubusercontent.com/assets/641411/22696386/ef57ed48-ed34-11e6-8cc1-e271ebb660e4.png)

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/22694468/8712e248-ed2e-11e6-8da0-ae0a0351eb4d.png)

**Comment by robertkapa** [comment]
resolvido.
