### ISSUE TITLE
[TFC] bug nos formulários dos comentários

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#58]
Preste atenção na posição dos nomes de cada caixa, tem um item "Site" que não é para aparecer e o resultado ao clicar o botão "Enviar" é diferente nas duas versões do site.

**Comment by anatolezano** [comment]
Como deve ser:
![image](https://cloud.githubusercontent.com/assets/25586548/22694576/e9bda874-ed2e-11e6-9de9-67b5cf3bd43a.png)

Como está:
![image](https://cloud.githubusercontent.com/assets/25586548/22694585/f0ed7110-ed2e-11e6-9597-7239f081123d.png)

**Comment by robertkapa** [comment]
deve ser um bug de javascript. O formulário quebrou e está sem os hints internos.

**Comment by gusgustavo** [comment]
Ok, resolvido.
