### ISSUE TITLE
[TFC] Problema com a página Notícias

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#59]
No site antigo, não existia a página "Notícias" no header. O leitor vê separadamente uma lista das matérias na categoria "Notícias" ao clicar no final do box roxo na home e uma lista das matérias na categoria "Para Saber +" ao clicar no final do box rosa na home. Com esse novo botão, seria possível criar uma lista única para as duas categorias (elas ainda poderão ser vistas separadamente ao clicar nos boxes)? Além disso, a lista está totalmente desconfigurada.

**Comment by anatolezano** [comment]
http://institutotim.gus.computer/noticias/
![image](https://cloud.githubusercontent.com/assets/25586548/22694785/a683c060-ed2f-11e6-9f99-6c2e0bd6fc83.png)

**Comment by robertkapa** [comment]
@anatolezano infelizmente não é possível porque foge do escopo desse trabalho com o @gusgustavo 

Combinamos com @gusgustavo, por hora, apenas a mudança de header e footer e os eventuais ajustes resultantes da quebra que isso causaria. Mas o item que vc aponta demandaria o desenvolvimento de uma nova página mesmo, algo que não existe hoje em dia. 


Veja como é a página hoje: http://timfazciencia.com.br/noticias/

Veja como está no ambiente de teste: http://institutotim.gus.computer/noticias/

@anatolezano duas sugestões possíveis: 
- Fazer outro escopo de trabalho que contemple essa nova funcionalidade. Isso poderia ser feito depois de terminada a mudança dos headers e footer e demandaria orçamento do projeto;
- Manter a página notícias e criar um novo item de menu com a página "para saber +", mantendo como está.

**Comment by anatolezano** [comment]
Eu nem sabia que existia uma página dessas no site atual! Ela não aparece em nenhum link do site. De qualquer forma, podemos então linkar por enquanto o botão "Notícias" do header com essa página: http://timfazciencia.com.br/categoria/noticias/? Não posso escolher uma das sugestões sem validar antes com a Carol.

**Comment by robertkapa** [comment]
ok! 

Resolução por hora dessa issue: linkar o item notícias para essa página 

http://institutotim.gus.computer/categoria/noticias/

**Comment by gusgustavo** [comment]
Ok. Resolvido.
