### ISSUE TITLE
[TFC] Disposição dos boxes no formulário de inscrições

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#60]
Os boxes estão ao lado das descrições, quando deveriam estar abaixo.

**Comment by anatolezano** [comment]
Como deve ser:
![image](https://cloud.githubusercontent.com/assets/25586548/22694936/298c9f04-ed30-11e6-90ee-e9a68fff1a1e.png)

Como está:
![image](https://cloud.githubusercontent.com/assets/25586548/22694946/2edf0a0a-ed30-11e6-95ce-0b335f325966.png)

**Comment by robertkapa** [comment]
resolvido.
