### ISSUE TITLE
[TFC] Quebra no box "Envie seu trabalho" nas páginas internas

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#61]
O box "Envie seu trabalho" aparece quebrado em páginas internas como "Notícias" e "Participe", em que ele está na lateral.

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/22695043/80d043f6-ed30-11e6-8a4b-4921ed5130ed.png)

**Comment by robertkapa** [comment]
resolvido.
