### ISSUE TITLE
[TFC] Indicador de curtidas no Facebook e Twitter

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#62]
Não está mais aparecendo o número de curtidas no Face e no Twitter abaixo das matérias. Veja só a diferença. 

Comportamento esperado: 
![selecao_018](https://cloud.githubusercontent.com/assets/641411/22697804/c2892a84-ed39-11e6-9a8f-4a12365a64a9.png)

Como está: 
![selecao_019](https://cloud.githubusercontent.com/assets/641411/22697811/c63631fe-ed39-11e6-8770-c5a1a2e1d5b3.png)

**Comment by anatolezano** [comment]
Como deve aparecer: 
![image](https://cloud.githubusercontent.com/assets/25586548/22695183/0386d65c-ed31-11e6-89e7-0145980ebc72.png)

Como está aparecendo:
![image](https://cloud.githubusercontent.com/assets/25586548/22695191/09cb6a1e-ed31-11e6-9665-c5f2311ca20c.png)

**Comment by gusgustavo** [comment]
Esse indicador só funcionará no site em produção, pois ele checa se o link da matéria (por exemplo, http://institutotim.gus.computer/noticias/tfc-inspira-tema-de-pesquisa-em-mestrado/) foi compartilhado. Como o domínio em homologação é diferente (e nunca foi compartilhado), nenhum resultado aparece.

**Comment by robertkapa** [comment]
ok
