### ISSUE TITLE
[AWC] Pop-up das inscrições para a 2ª chamada não aparece ao abrir o site

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#63]
Como deve ser (com overlay modal):
![selecao_115](https://cloud.githubusercontent.com/assets/641411/23023353/608e474c-f43c-11e6-83be-fde71aaa3bb2.png)

Como está: 
![selecao_116](https://cloud.githubusercontent.com/assets/641411/23023360/6604631e-f43c-11e6-891e-d3c41c0249d9.png)

**Comment by gusgustavo** [comment]
Uma dúvida: esse conteúdo foi publicado em que dia? 
Talvez ele tenha sido depois da clonagem do ambiente de homolgação.

**Comment by anatolezano** [comment]
Se não me engano foi na última semana de janeiro ou primeira de fevereiro.

**Comment by gusgustavo** [comment]
@robertkapa, confere a data da clonagem do ambiente de homologação

**Comment by robertkapa** [comment]
foi clonado dia 03/02. Vamos aguardar para quando virar a chave, isto é, para quando aplicar o tema no produção para ver se o problema persiste.

**Comment by gusgustavo** [comment]
@robertkapa, aqui abriu o banner. Verifica se está tudo certinho.

**Comment by robertkapa** [comment]
ok

**Comment by anatolezano** [comment]
No meu eu já limpei o cache, mas não apareceu :(
