### ISSUE TITLE
[AWC] Link do logo Instituto TIM

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#65]
O logo do Instituto TIM no header está direcionando para a página da TIM, quando deve ser para o Instituto TIM. Tanto o logo do header quanto do footer devem direcionar para uma nova aba.

**Comment by gusgustavo** [comment]
Ok, resolvido.

**Comment by anatolezano** [comment]
O logo do footer ainda está abrindo na mesma página. Pode direcioná-lo para uma nova aba?

**Comment by gusgustavo** [comment]
Ops, havia um pequeno erro de digitação no html, agora foi. @robertkapa

**Comment by robertkapa** [comment]
@gusgustavo o logo do institutotim está abrindo na mesma página. Podes colocar um target="_blank" para que abra numa nova aba?

**Comment by gusgustavo** [comment]
@robertkapa, você limpou o cache? Veja no site em produção

**Comment by robertkapa** [comment]
ok.

**Comment by anatolezano** [comment]
Também limpei o cache e o link do footer ainda abre na mesma aba.
