### ISSUE TITLE
[AWC] Fontes do footer

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#66]
Os itens do footer estão de acordo com os do header, mas parecem estranhos dessa forma. Será que dá para posicioná-los de outra maneira ou mudar o tamanho ou a cor da fonte, algo assim? Felipe, tem alguma sugestão?

**Comment by robertkapa** [comment]
Segue minha sugestão: 

```
<!--     Start Footer AWC -->
    <footer class="section section-primary">
      <div class="container">
        <div class="row">
          <div class="col-md-1">O que é?</div>
          <div class="col-md-1">Como fazemos?</div>
          <div class="col-md-1">Agenda</div>
          <div class="col-md-1">Inscreva-se</div>
          <div class="col-md-1">Notícias</div>
          <div class="col-md-1">FAQ</div>
          <div class="col-md-1">Equipe</div>
          <div class="col-md-5"> 
             <div class="row text-center">

               <a href="https://institutotim.org.br"><img src="img/logo_header_institutotim.png"></a><br><br>
               <h5 class="footertitle">Instituto TIM nas Redes</h5>
               <a href="#"><i class="fa fa-fw hub fa-lg text-inverse fa-twitter"></i></a>
             </div>
        </div>
         <div class="col-md-12 col-md-12 col-sm-12 col-xs-12 text-center footertitle">
           <div class="row"><br>
             Copyright TIM Celular 2016 - Todos os direitos reservados.
          </div>
        </div>
      </div>
    </footer>
<!--     END Footer AWC -->
```

**Comment by anatolezano** [comment]
Gostei mais dessa fonte. Mas acho que o inscreva-se tem que ficar em uma linha linha só, fica estranho em duas linhas. E será que em negrito fica melhor? Assim como no site do IT?

**Comment by gusgustavo** [comment]
@robertkapa as colunas não devem ser fixas e iguais em todos os sites?

**Comment by robertkapa** [comment]
> @robertkapa as colunas não devem ser fixas e iguais em todos os sites?

yep. Mas nesse caso vai dar uma tremenda dor de cabeça. Melhor seguir a sugestão que eu estou dando.

**Comment by robertkapa** [comment]
>  Mas acho que o inscreva-se tem que ficar em uma linha linha só, fica estranho em duas linhas. E será que em negrito fica melhor? Assim como no site do IT?

A ana tem razão, vou preparar esse ajuste e colo o código aqui. A fonte tem de ser igual do site do Instituto.

**Comment by anatolezano** [comment]
Pessoal, acho que a fonte está ok agora! Mas o espaçamento entre os itens está bem diferente, alguns distantes e outros próximos entre si. Dá para alinhar de uma forma mais equivalente?

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/23626486/d7319266-028b-11e7-9edc-18e1eb9aa0fa.png)

**Comment by anatolezano** [comment]
Essa issue consta como "Closed", mas o espaçamento entre os itens está todo zuado. Não dá para alinhá-los de forma equivalente?

**Comment by anatolezano** [comment]
Problema de espaçamento resolvido!
