### ISSUE TITLE
[AWC] Ícone do Twitter

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#67]
O link para o Twitter no header deve abrir em uma nova aba. Além disso, não deveria ter um ícone no footer também?

**Comment by gusgustavo** [comment]
Ok, feito.

**Comment by anatolezano** [comment]
Os links não estão abrindo em uma nova aba.

**Comment by robertkapa** [comment]
Foi incluido o ícone no footer, mas não está abrindo em outra aba/janela. Estou reabrindo a issue.

**Comment by robertkapa** [comment]
tem que colocar target="_blank" na chave 
```
<a href=""  target="_blank">
```

**Comment by gusgustavo** [comment]
Ok, feito

**Comment by robertkapa** [comment]
testei e continua abrindo na mesma aba.

**Comment by gusgustavo** [comment]
@robertkapa, você limpou o cache?

**Comment by robertkapa** [comment]
ok

**Comment by anatolezano** [comment]
Também limpei o cache e não abre em nova aba
