### ISSUE TITLE
[AWC] Direcionamento dos itens do menu

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#69]
Quando eu clico nos itens do menu que direcionam para diferentes partes da home, no site atual a home vai rolando automaticamente até o quadro selecionado. Neste novo site, ele vai direto para o quadro selecionado, sem rolar pela home.

**Comment by robertkapa** [comment]
Esse problema reportado pela @anatolezano é devido a termos retirado o menu fixo (de acordo com novo guide da TIM não podemos mais usar menu fixo). Uma vez que não temos mais como colocar menu fixo, perdemos essa funcionalidade de slowmotion ao navegar pelos itens no one page scrolling. Estou fechando essa issue portanto.
