### ISSUE TITLE
[IT] O texto da Missão está em negrito

### ISSUE THREAD

**Issue by gusgustavo** [robertkapa/institutotim-header-footer#7]

**Comment by gusgustavo** [comment]
O texto da missão está usando a fonte TIMSansWeb. Ela está sobrepondo a fonte default do site. Devo alterar?

**Comment by robertkapa** [comment]
O problema é que essa fonte foi alterada. Antes a TIMSansWeb era uma coisa, hj ela mudou e é isso daí. Podemos deixar assim por hora, vamos mexer com itens prioritários e depois voltamos para isso se houver tempo. Vou mover essa issue para wishlist.

**Comment by anatolezano** [comment]
Dá tempo de resolver esse item?

**Comment by gusgustavo** [comment]
Oi, o problema é o tamanho da fonte, por isso ela dá a impressão de estar em negrito. Posso diminuir a fonte se vocês quiserem.

**Comment by anatolezano** [comment]
É que se diminuir a fonte, vai ficar pouco texto pro espaço do quadro azul. Vamos então deixar assim mesmo e encerrar essa issue.
