### ISSUE TITLE
[AWC] Títulos indevidos nas páginas de inscrições e FAQ

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#70]
As páginas de INSCRIÇÕES e FAQ não têm os títulos no topo. 

Como deve ser: 
![selecao_123](https://cloud.githubusercontent.com/assets/641411/23030344/a73f66ea-f454-11e6-948c-51d9cfc41e7f.png)

Como está: 
![selecao_125](https://cloud.githubusercontent.com/assets/641411/23030435/e4c72a8e-f454-11e6-9a6a-7ccadfff2acc.png)

**Comment by robertkapa** [comment]
persiste em inscrições

**Comment by anatolezano** [comment]
Erro persiste na página de inscrições

**Comment by gusgustavo** [comment]
Arrumado. Verifique se está ok agora.

**Comment by anatolezano** [comment]
Está certo, obrigada!
