### ISSUE TITLE
[AWC] Problemas na página de Notícias

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#71]
# Item 1
- [x] Largura está diferente
Como está:
![selecao_118](https://cloud.githubusercontent.com/assets/641411/23023636/a5bec7be-f43d-11e6-9a66-19d62ea89f01.png)

Como está em produção: 
![selecao_119](https://cloud.githubusercontent.com/assets/641411/23023629/9e055984-f43d-11e6-8a4a-ace59b646d2c.png)

# Item 2
- [ ] Nos widgets, no produção há um widget com as categorias, no homologação não. 
Como está:
![noticias awc2](https://cloud.githubusercontent.com/assets/641411/23023776/3760ea8a-f43e-11e6-9a42-e1d12e731ac0.png)

Como está em produção:
![noticias awc](https://cloud.githubusercontent.com/assets/641411/23023771/2f9947b6-f43e-11e6-87ee-7cb91515497e.png)

# Item 3
- [x] Não tem paginação. As notícias viram uma tripa gigante ao longo da página

**Comment by robertkapa** [comment]
# Item 1
Quanto ao item1, acredito que ficou melhor agora pois está se adequando melhor ao menu. Devemos manter dessa forma, então estou marcando como resolvido. 

# Item 2
O item2 tem de ser resolvido. @gusgustavo acredito que é só acrescentar o widget de categorias. 
@anatolezano é possível manter o widget de tags? 

# Item 3
Quanto ao item3 está fora do escopo. Esse é um problema de projeto do site original.

**Comment by anatolezano** [comment]
Item 1: OK
Item 2: Por mim tudo bem manter o widget de tags, mas tem como manter só as 30 tags mais frequentes, ou algo assim? (se eu puder controlar isso do WordPress, melhor ainda) Senão fica uma coluna gigante de tags.
Item 3: OK :(

**Comment by robertkapa** [comment]
resolvido.

**Comment by anatolezano** [comment]
Lembrando apenas que aguardamos a ajuda da equipe LFDB para recuperar os itens que pagamos para o Uiu acrescentar na página de notícias no ano passado e que sumiram.

**Comment by anatolezano** [comment]
Ainda precisa recuperar os itens que o Uiu acrescentou.
