### ISSUE TITLE
[TFC] Logo de TFC abre em uma nova página

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#76]
Oi, pessoal, vi que os novos header e footer já estão publicados no site de TFC. Percebi que, ao clicar no logo de TFC, a home abre em uma nova janela. Isso só tem que acontecer com o logo do Instituto TIM, já que o logo de TFC tem a função de conduzir o usuário de volta à página inicial.

**Comment by robertkapa** [comment]
resolvido.
