### ISSUE TITLE
Quando a gente clica nas páginas Notícias ou Contato, os botões ficam marcados

### ISSUE THREAD

**Issue by gusgustavo** [robertkapa/institutotim-header-footer#8]

**Comment by gusgustavo** [comment]
Resolvido

**Comment by robertkapa** [comment]
no chrome, problema persiste: 

![selecao_102](https://cloud.githubusercontent.com/assets/641411/22430770/662a33b2-e6f6-11e6-9e7d-eb46657558a1.png)

**Comment by gusgustavo** [comment]
@robertkapa, hm, você limpou o cache do navegador ou usou a aba anônima?

**Comment by robertkapa** [comment]
vish, acabei de ver que era cache... mas agora apareceram outros bugs que estavam resolvidos antes....

**Comment by gusgustavo** [comment]
@robertkapa, entao o botao do menu continua apresentando o comportamento descrito acima? 
Se negativo, fecha a issue.

**Comment by robertkapa** [comment]
ok! resolvido.
