### ISSUE TITLE
[TFC] Versão Desktop - Espaços em branco entre header e páginas e footer e páginas

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#83]
O header e o footer precisam estar grudados ao restante da página.

**Comment by anatolezano** [comment]
![image](https://cloud.githubusercontent.com/assets/25586548/24046697/2b68d244-0b02-11e7-8525-7eeb0bb6e5a8.png)

![image](https://cloud.githubusercontent.com/assets/25586548/24046704/2ffa02d8-0b02-11e7-8691-43e43740eb45.png)

**Comment by anatolezano** [comment]
Resolvido no header, não no footer.

**Comment by anatolezano** [comment]
Pessoal, além disso, percebemos que a ilustração dos mascotes das sete operações na home está invadindo um pouco o header. É coisa de milímetros, mas talvez isso também possa estar causando o problema de desalinhamento no mobile.

**Comment by robertkapa** [comment]
testado no firefox e no chrome. Está funcionando como deveria. 

![selecao_031](https://cloud.githubusercontent.com/assets/641411/24568533/b6b56ac4-1638-11e7-9264-9e51d9335652.png)

![selecao_030](https://cloud.githubusercontent.com/assets/641411/24568542/ba428f5a-1638-11e7-8772-30fb9a8c9652.png)

**Comment by anatolezano** [comment]
@robertkapa Ainda persiste o que eu tinha falado sobre a ilustração: "Pessoal, além disso, percebemos que a ilustração dos mascotes das sete operações na home está invadindo um pouco o header. É coisa de milímetros, mas talvez isso também possa estar causando o problema de desalinhamento no mobile." Se você não estiver percebendo eu te mostro, mas, como disse, talvez seja esse detalhezinho que esteja ajudando a provocar o desalinhamento no mobile.

**Comment by robertkapa** [comment]
pode dar um print para ficar registrado, @anatolezano ?

**Comment by anatolezano** [comment]
Esse é o máximo de zoom que consegui dar para mostrar pra vocês:
![image](https://cloud.githubusercontent.com/assets/25586548/24622976/49c9f186-187d-11e7-984a-c38c3e565f65.png)

**Comment by anatolezano** [comment]
Dá para ver?
