### ISSUE TITLE
[TIM Tec] Filtro "Não respondido" não funciona no Fórum

### ISSUE THREAD

**Issue by anatolezano** [robertkapa/institutotim-header-footer#90]
Quando clicamos no filtro "Não respondido", ele filtra as mensagens Abertas. Não sei dizer se esse erro já existia antes da mudança, eu nunca havia entrado nessa página.

**Comment by gusgustavo** [comment]
Oi, isso não está relacionado com as mudanças realizadas.

**Comment by anatolezano** [comment]
Ok!
